version: '3.8'

services:
  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    container_name: monitor
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    user: "0:0"  # Run as root to access Docker socket
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
