version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-m", "8222"]
    networks:
      - bus
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  agent-1:
    build:
      context: ./agents
      dockerfile: Dockerfile
      args:
        - AGENT_UID=1001
        - AGENT_GID=1001
    image: ai-agent-1:latest
    container_name: agent-1
    restart: unless-stopped
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-1
      - NATS_URL=nats://nats:4222
      - SHARED_DIR=/shared
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-1.5-flash
    volumes:
      - ./shared:/shared
    networks:
      - bus
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /home/agent:uid=1001,gid=1001
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  agent-2:
    build:
      context: ./agents
      dockerfile: Dockerfile
      args:
        - AGENT_UID=1002
        - AGENT_GID=1002
    image: ai-agent-2:latest
    container_name: agent-2
    restart: unless-stopped
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-2
      - NATS_URL=nats://nats:4222
      - SHARED_DIR=/shared
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-1.5-flash
    volumes:
      - ./shared:/shared
    networks:
      - bus
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /home/agent:uid=1002,gid=1002
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  agent-3:
    build:
      context: ./agents
      dockerfile: Dockerfile
      args:
        - AGENT_UID=1003
        - AGENT_GID=1003
    image: ai-agent-3:latest
    container_name: agent-3
    restart: unless-stopped
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-3
      - NATS_URL=nats://nats:4222
      - SHARED_DIR=/shared
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-1.5-flash
    volumes:
      - ./shared:/shared
    networks:
      - bus
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /home/agent:uid=1003,gid=1003
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    image: ai-flock-monitor:latest
    container_name: monitor
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bus
    depends_on:
      - nats
      - agent-1
      - agent-2
      - agent-3
    user: "0:0"  # Run as root to access Docker socket
    security_opt:
      - no-new-privileges:false  # Allow privileges to access Docker

networks:
  bus:
    driver: bridge