version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-m", "8222"]
    networks:
      - bus
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  agent:
    build:
      context: /vagrant/agents
      dockerfile: Dockerfile
    image: ai-agent:latest
    restart: unless-stopped
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-${AGENT_NUMBER:-1}
      - NATS_URL=nats://nats:4222
      - SHARED_DIR=/shared
    volumes:
      - /vagrant/shared:/shared
    networks:
      - bus
    read_only: true
    tmpfs:
      - /tmp
      - /run
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
          pids: 50
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  bus:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16